apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: exemplo-argo
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/Andretalyss/argocd.git
        targetRevision: HEAD
        path: .
        directory:
            recurse: true
    destination:
        server: https://kubernetes.default.svc
        namespace: argo-exemplo
    syncPolicy:
        automated:
            prune: false
            selfHeal: false
