apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-exemplo
  namespace: argo-exemplo
  labels:
    app: argo-exemplo
  annotations:
spec:
  selector:
    matchLabels:
      app: argo-exemplo
  replicas: 1
  template:
    metadata:
      labels:
        app: argo-exemplo
    spec:
      containers:
      - name: argo-exemplo
        image: nginx:1.20.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
