apiVersion: v1
kind: Service
metadata:
    name: example-service
    namespace: argo-exemplo
spec:
    selector:
        app: exemplo-argo
    ports:
     - protocol: TCP
       port: 80
       targetPort: 5000
